name: rhythm
description: A music player app with background playback, notification controls, and lock screen player.

publish_to: 'none'

version: 1.0.3
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  file_picker: ^10.3.8
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  dio: ^5.3.0
  provider: ^6.0.5
  lottie: ^2.4.2
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  audio_video_progress_bar: ^2.0.3
  on_audio_query: ^2.9.0
  dart_des: ^1.0.2
  fuzzywuzzy: ^1.2.0
  crypto: ^3.0.3
  path_provider: ^2.1.1
  package_info_plus: ^4.0.3
  open_filex: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#028A7C"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/assets/animation/